### ISSUE TITLE
Help to set backup intervals

### ISSUE THREAD

**Issue by TDivisionX** [HeatherComputer/AdvancedBackups#88]
Hi @HeatherComputer, how can i only take a backup of my server at 5am every two days? I'm having trouble to set the correct ranges in the config file. Glad if u can help me...

**Comment by HoldYourWaffle** [comment]
I can't look into it in detail right now, but as far as I know the "every two days" part is currently impossible.
You can set the schedule to real-world time with:
```
config.advancedbackups.frequency.uptime=false
```
And schedule it for 5am with:
```
config.advancedbackups.frequency.schedule=5:00
```
But as far as I know there's no way to skip a day.

@HeatherComputer could be worth looking at using the standardized (and infinitely flexible) cron syntax for backup schedules in the future.

**Comment by HeatherComputer** [comment]
There are technically the min and max frequency options, which could somewhat create the desired effect - but otherwise yeah, the current scheduling can't skip a day.

**Comment by HeatherComputer** [comment]
> @HeatherComputer could be worth looking at using the standardized (and infinitely flexible) cron syntax for backup schedules in the future.


Cron syntax is definitely an option, but I had seen too many people struggling to understand it and that's why I chose not to go with it. Perhaps it could be implemented as an optional feature..?

**Comment by TDivisionX** [comment]
Thanks for the answers! I was able to configure the backup to occur every day at 5pm as you said

**Comment by HeatherComputer** [comment]
Thinking of this more during my temporary access to my main pc, cron syntax would pair *really* nicely with the profiles plan..
