### ISSUE TITLE
Feature request : Automatically restore the most recent full backup before when trying to restore a partial backup

### ISSUE THREAD

**Issue by Rcpentuy** [HeatherComputer/AdvancedBackups#92]
**Is your feature request related to a problem? Please describe.**
It seems that i have to manually restore to the most recent full backup before my selected partial backup every time, which makes the rollback process a bit more inconvenient. (Actually i am quite curious what will happen if i just skip that first step. )

**Describe the solution you'd like**
let the mod detect the most recent full backup before the selected partial backup and automatically restore it in advance so that the user only need to communicate with the shell script once to rollback. 

**Describe alternatives you've considered**

**Additional context**

**Comment by HeatherComputer** [comment]
This is already done - and the console should give that information when restoring a partial.

Has this not been the case from your experience?

**Comment by Rcpentuy** [comment]
Apologies for misunderstanding the README file. I reviewed the documentation again and realized that I incorrectly referred to the "MANUAL BACKUP RESTORATION - FULL BACKUP" section for command-line usage. Thank you for the clarification!
