### ISSUE TITLE
Bug report : Advanced backup 3.6.4 or any version doesnt work for modded fabric server (MC 1.21, loader 0.16.9)

### ISSUE THREAD

**Issue by StarB0b** [HeatherComputer/AdvancedBackups#99]
**Describe the bug**
I installed the mod from curseforge and modrinth, put the mod in the mod folder of my server. Fabric server loader ran, saying there are incompatible mods, seen in the image below. The server works when i remove it.
**To Reproduce**

follow the steps to get the server running, put the mod in the mod folder and it it doesnt run as it should.

**Expected behavior**

I put the mod in the mod folder, run the fabric server .jar, then the server to just work, like how it works on my personal modrinth profile. 

**Screenshots**
![image](https://github.com/user-attachments/assets/b80b0fe8-517f-4ade-8ff7-2da49b795ec2)

**Versioning (please complete the following information):**
 - OS: Windows 10 Pro, 22h2
 - Minecraft Version(s): 1.21
 - Modloader(s): 0.16.9
 - Mod Version: 3.6.4, 3.6
**Additional context**
Reinstalled the server, fabric, and all the mods. I assume its some user error, im simply looking for some troubleshooting tips.

thank you.

**Comment by HeatherComputer** [comment]
Advanced Backups depends on Fabric Api. This is a separate mod to the Fabric modloader, for reasons beyond my comprehension.

You can find it at https://modrinth.com/mod/fabric-api/

If your issue persists after getting the Fabric Api mod, feel free to reopen the issue along with providing a `latest.log` and full modlist.
